### ISSUE TITLE
Set up Redis as primary cache

### ISSUE THREAD

**Issue by singhpratyush** [anyaudio/anyaudio-server#139]
As of now, each time a request is made, Youtube is scraped or `youtube-dl` is called to return results. This can be made much faster if we introduce Redis datastore as the primary cache, significantly reducing response time for `youtube-dl` queries.

The time for key expiry can be safely set to 5.5 hours.

On miss, we can go to scrape Youtube.

**Comment by aviaryan** [comment]
We can use [Redismin](https://www.redsmin.com/) or [RedisLabs](https://redislabs.com/) for hosting. I will prefer Redismin because it allows a generous 100k keys for the free plan.

**Comment by singhpratyush** [comment]
@aviaryan: Sounds great.

**Comment by singhpratyush** [comment]
Fixed in 64cc3df2b7f58ac3f02db08289a32d9589dd2cce with in-house Redis store.
