### ISSUE TITLE
Set up ngnix on AWS

### ISSUE THREAD

**Issue by singhpratyush** [anyaudio/anyaudio-server#146]
Currently, `anyaudio` serves the requests directly through `gunicorn`. Requirement is to use `ngnix` (engine-x) as load balancer and reverse proxy on the AWS instance.

**Comment by aviaryan** [comment]
@singhpratyush Since we are only using a single server right now, do we really need to setup nginx?

**Comment by singhpratyush** [comment]
It will ensure internal load balancing and better performance. But I too have started thinking that it is irrelevant as we only have single vCPU with us. Also, since the deployment is working fine, we can postpone this issue.

**Comment by singhpratyush** [comment]
Not needed right now.
