### ISSUE TITLE
Support for multiple audio formats

### ISSUE THREAD

**Issue by Nilesh4145** [anyaudio/anyaudio-server#151]
[DASH](https://www.google.co.in/url?sa=t&rct=j&q=&esrc=s&source=web&cd=13&cad=rja&uact=8&ved=0ahUKEwjw98nf9bDUAhVML48KHfB8DMgQFghrMAw&url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FDynamic_Adaptive_Streaming_over_HTTP&usg=AFQjCNHntcdqa7FrH6FmSgc9jt36tbfgZw&sig2=7EKQwNxysaRjGyIriVzYmg) integration be helpful for streaming audio in various file formats depending on the underlying bandwidth.

**Comment by singhpratyush** [comment]
Tha API already provides a way to get songs in different audio format. Please take a look at the API docs mentioned in project README.
