### ISSUE TITLE
add user credentials for keep music on the server?

### ISSUE THREAD

**Issue by roboto-cloud** [anyaudio/anyaudio-server#154]
Hi, know if save on local feature is available?
something like:
https://github.com/streamlist/streamlist
thanks in advance,

**Comment by singhpratyush** [comment]
Yes, you can download the songs and save them locally.

**Comment by roboto-cloud** [comment]
I don't see AnyLogin button... can you tell me where it is?
I want keep the music on the server and access it across devices using login credential...
thanks :)

**Comment by singhpratyush** [comment]
Okay, so there is no login feature. The goal of the service is to provide simple music searching and downloading features.

If you want to keep your music and access it later, AnyAudio is probably not the right service. You can access any music here but can't store your own songs.

**Comment by singhpratyush** [comment]
Please reopen if necessary/
