### ISSUE TITLE
Error while retrieving items of playlist

### ISSUE THREAD

**Issue by twenk11k** [anyaudio/anyaudio-server#161]
Length and uploader of items in the trending playlist is return a html code through json.
It's only working when i use "anyaudio.in" but not working on my server.
I've tried search and it's working as expected. 
How can i solve this problem ?

**Comment by singhpratyush** [comment]
@twenk11k Do you have an example request and response?

**Comment by twenk11k** [comment]
@singhpratyush I have explained step by step through this link. : https://gist.github.com/twenk11k/be292ec573cb85f4d09fcd6478160d6b
I had set up server on docker container and use http:// for now.

**Comment by singhpratyush** [comment]
HTML in the description is not an issue. It is supposed to be that way.

**Comment by twenk11k** [comment]
Length supposed to be "3:44" instead of html code as you see in those screenshots. There must be an error on the server side but i can't figure it out the reason behind of it.

**Comment by twenk11k** [comment]
I have solved the issue on another server. I still don't know why old server has this issue. 
Also i found out that in Android devices below api 24, all urls which has spaces would produce 400 bad request error(invalid html version). For fix this particular issue spaces of urls need to replace with "%20" before request from Volley.
`url.replaceAll(" ","%20")`
